### ISSUE TITLE
amass failed

### ISSUE THREAD

**Issue by dorkerdevil** [c0rvax/project-black#67]
**Describe the bug**
amass failed when i try to run

**To Reproduce**
1. create a new project
2. now add any domain to scope 
3. now launch task > Amass 
4. amass failed error shows up

**Expected behavior**

**Screenshots**
![assa](https://user-images.githubusercontent.com/15796745/59973375-db785f00-95bc-11e9-8c56-318bfa7d84d5.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome
 - Environment: standalone launch

**Additional context**

**Comment by dorkerdevil** [comment]
all the options in amass are throwing amass error , not working any more, alas! the whole package is broken
![assa](https://user-images.githubusercontent.com/15796745/59973422-678a8680-95bd-11e9-809a-52b0d2a3b53b.png)

**Comment by c0rvax** [comment]
Hi, thanks for creating the ticket. I think this problem has already been addressed by this pull request https://github.com/c0rvax/project-black/pull/66 

So i think that you might want to do 
```git pull```
and then rebuild the container for amass
```docker-compose build black_amass```

Let me know if that will help.

**Comment by c0rvax** [comment]
Hi, i will close this for now, if the solution is not what you want, please reopen or comment.
