### ISSUE TITLE
[Bug] Can not finish install

### ISSUE THREAD

**Issue by lovelyjuice** [c0rvax/project-black#68]
**Describe the bug**
Can not finish install with `docker-compose up`,  building stoped after install git.

**Screenshots**
![image](https://user-images.githubusercontent.com/20644461/63637967-432e5180-c6b5-11e9-8e14-8d2cceb26d8f.png)

**Desktop (please complete the following information):**
 - OS: kali
 - Browser: [e.g. chrome, safari]
 - Environment: Docker containers

**Additional context**
Because of the bad China Mobile network, I have tried to execute  `docker-compose up` for serveral times. Maybe the `1 not upgrade`  cause this bug？

**Comment by c0rvax** [comment]
Hi @lovelyjuice 

Thanks for using the template for creating the bug! Right now i am not making new features or develop the project actively, but i do fix bugs.

So could you tell me for approximately how long have you been waiting before sending SIGSTP (ctrl+z)?
The terminal just freezes? 
Have you checked current processes to see whether docker or/and docker-compose is actively running?

It is unlikely that the reason here is the `apt install`. I would say that either the download is being very slow for you or the machine is not very good and the installation process is slow there.

**Comment by lovelyjuice** [comment]
@c0rvax I tried again, and wait for half an hour, but the building is still can't go on.

![image](https://user-images.githubusercontent.com/20644461/63674589-6e31b600-c819-11e9-9712-f755d1a94418.png)

And then, I didn't interrupt or hang on the `docker-compose` but execute `ps aux` to show current processes. It shows that the process is running, I bold the key line near bottom.
>root@kali:/opt/project-black# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
.......
root        331  0.0  0.2  25264  8652 ?        Ss   15:08   0:00 /lib/systemd/systemd-journald
root        343  0.0  0.2  23748  6400 ?        Ss   15:08   0:00 /lib/systemd/systemd-udevd
root        369  0.0  0.2   8084  7456 ?        Ss   15:08   0:00 /usr/sbin/haveged --Foreground --verbose=1 -w 1024
root        511  0.0  0.2  19508  7164 ?        Ss   15:09   0:00 /lib/systemd/systemd-logind
message+    512  0.0  0.1   9748  4844 ?        Ss   15:09   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root        514  0.0  0.0   8440  2572 ?        Ss   15:09   0:00 /usr/sbin/cron -f
root        515  0.0  0.1  82256  3676 ?        Ssl  15:09   0:00 /usr/sbin/irqbalance --foreground
root        516  0.0  0.5 332840 15952 ?        Ssl  15:09   0:00 /usr/sbin/NetworkManager --no-daemon
root        519  0.0  0.3 318332 10016 ?        Ssl  15:09   0:00 /usr/sbin/ModemManager --filter-policy=strict
root        521  0.0  0.1 225824  4620 ?        Ssl  15:09   0:00 /usr/sbin/rsyslogd -n -iNONE
root        540  0.0  0.0      0     0 ?        I<   15:09   0:00 [kworker/u257:2-hci0]
root        585  0.0  0.2 236716  7760 ?        Ssl  15:09   0:00 /usr/lib/policykit-1/polkitd --no-debug
root        599  0.0  0.2 313396  7120 ?        SLsl 15:09   0:00 /usr/sbin/lightdm
root        636  0.1  2.9 406672 89020 tty7     Ssl+ 15:09   0:04 /usr/lib/xorg/Xorg :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
root        637  0.0  0.0   2648  1680 tty1     Ss+  15:09   0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
root        664  0.0  0.1   9488  6032 ?        S    15:09   0:00 /sbin/dhclient -d -q -sf /usr/lib/NetworkManager/nm-dhcp-helper -pf /run/dhclient-eth0.pid -lf /var/lib/
root        980  0.0  0.0 179616   724 ?        Ssl  15:09   0:00 /usr/bin/vmhgfs-fuse -o subtype=vmhgfs-fuse,allow_other /mnt/hgfs
root       1008  0.0  0.0 168160   624 ?        Ssl  15:09   0:00 /usr/sbin/vmware-vmblock-fuse -o subtype=vmware-vmblock,default_permissions,allow_other /var/run/vmblock
root       1033  0.0  0.4 155816 13064 ?        Sl   15:09   0:01 /usr/sbin/vmtoolsd
root       1099  0.0  0.3  40244 11040 ?        S    15:09   0:00 /usr/lib/vmware-vgauth/VGAuthService -s
root       1180  0.0  0.3 166872  9588 ?        Sl   15:15   0:00 lightdm --session-child 14 23
root       1185  0.0  0.3  21364  9264 ?        Ss   15:15   0:00 /lib/systemd/systemd --user
root       1186  0.0  0.0 104940  2412 ?        S    15:15   0:00 (sd-pam)
root       1196  0.0  0.7 389596 24324 ?        S<sl 15:15   0:00 /usr/bin/pulseaudio --daemonize=no
root       1202  0.0  0.0   2388  1516 ?        Ss   15:15   0:00 /bin/sh /etc/xdg/xfce4/xinitrc -- /etc/X11/xinit/xserverrc
root       1210  0.0  0.1   9240  4420 ?        Ss   15:15   0:00 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-onl
root       1235  0.0  0.0   5852   488 ?        Ss   15:15   0:00 /usr/bin/ssh-agent x-session-manager
root       1245  0.0  0.5 212196 15632 ?        Sl   15:15   0:00 xfce4-session
root       1249  0.0  0.1  16720  5536 ?        S    15:15   0:00 /usr/lib/x86_64-linux-gnu/xfce4/xfconf/xfconfd
root       1253  0.0  0.1  80924  3252 ?        SLs  15:15   0:00 /usr/bin/gpg-agent --supervised
root       1255  0.0  0.7  67448 21544 ?        S    15:15   0:00 xfwm4 --display :0.0 --sm-client-id 2f492895a-f0cc-44e4-aa09-d15f57b05174
root       1258  0.0  0.7 218764 22128 ?        Sl   15:15   0:00 Thunar --sm-client-id 278928714-6df1-489e-8d4d-9e5a0447c00f --daemon
root       1261  0.0  0.2 240052  7232 ?        Ssl  15:15   0:00 /usr/lib/gvfs/gvfsd
root       1267  0.0  0.2 312484  6356 ?        Ssl  15:15   0:00 /usr/lib/at-spi2-core/at-spi-bus-launcher
root       1272  0.0  0.1   8972  4240 ?        S    15:15   0:00 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-addre
root       1274  0.0  0.2 174140  6692 ?        Sl   15:15   0:00 /usr/lib/at-spi2-core/at-spi2-registryd --use-gnome-session
root       1277  0.0  1.0 276440 31524 ?        Sl   15:15   0:00 xfce4-panel --display :0.0 --sm-client-id 2b9760ea5-a912-446f-a835-33143a7abb5b
root       1279  0.0  0.4 246032 15220 ?        Ssl  15:15   0:00 xfsettingsd --display :0.0 --sm-client-id 278793d8d-78b9-4438-b6a9-7ff7f8ded099
root       1281  0.0  1.7 354988 54312 ?        Sl   15:15   0:01 xfdesktop --display :0.0 --sm-client-id 2efd476db-5dac-4f8c-b842-ba805e7a479a
root       1285  0.0  0.2 258412  8868 ?        Ssl  15:15   0:00 /usr/lib/upower/upowerd
root       1298  0.0  0.4 212536 14180 ?        Ssl  15:15   0:00 xfce4-power-manager --restart --sm-client-id 21b6a865d-42b2-4587-b0bc-aaef1a16e399
root       1304  0.0  0.1 311300  4612 ?        Sl   15:15   0:00 /usr/lib/geoclue-2.0/demos/agent
root       1314  0.0  1.1 369492 34636 ?        Sl   15:15   0:00 nm-applet
root       1323  0.0  0.6 278348 19932 ?        Sl   15:15   0:00 light-locker
root       1324  0.0  0.4 212276 13552 ?        Ssl  15:15   0:00 xfce4-power-manager
root       1333  0.0  0.1 159340  4956 ?        Sl   15:15   0:00 /usr/lib/dconf/dconf-service
root       1346  0.0  0.4  64240 15120 ?        S    15:15   0:00 /usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-1.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libsystr
root       1347  0.0  0.5 201072 15788 ?        Sl   15:15   0:00 /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
root       1349  0.0  0.5  65892 16748 ?        S    15:15   0:00 /usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-1.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libactio
root       1352  0.0  0.9 215180 28088 ?        Sl   15:15   0:01 /usr/lib/vmware-tools/sbin64/vmtoolsd -n vmusr --blockFd 3
root       1370  0.0  0.5 286196 17496 ?        Ssl  15:15   0:00 /usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd
root       1375  0.0  0.3 280312 11500 ?        Ssl  15:15   0:00 /usr/lib/gvfs/gvfs-udisks2-volume-monitor
root       1378  0.0  0.4 398528 12216 ?        Ssl  15:15   0:00 /usr/lib/udisks2/udisksd
root       1400  0.0  0.2 314180  7492 ?        Sl   15:15   0:00 /usr/lib/gvfs/gvfsd-trash --spawner :1.10 /org/gtk/gvfs/exec_spaw/0
root       1405  0.0  0.0      0     0 ?        I    15:15   0:00 [kworker/u256:0-events_unbound]
root       1406  0.0  0.1 164640  5544 ?        Ssl  15:15   0:00 /usr/lib/gvfs/gvfsd-metadata
root       1425  0.0  1.3 421736 41344 ?        Sl   15:15   0:01 xfce4-terminal
root       1429  0.0  0.1   7984  4888 pts/0    Ss   15:15   0:00 bash
root       1450  0.2  2.8 1073996 86884 ?       Ssl  15:18   0:03 /usr/sbin/dockerd -H fd://
root       1457  0.1  1.1 1025892 36024 ?       Ssl  15:18   0:02 docker-containerd --config /var/run/docker/containerd/containerd.toml --log-level info
***root       1701  0.0  1.6  72616 48920 pts/0    S+   15:18   0:01 /usr/bin/python3 /usr/bin/docker-compose up***
root       1729  0.0  0.3 847156 11468 ?        Sl   15:18   0:00 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.
root       1749  0.0  0.0   4280   692 ?        Ss   15:18   0:00 /bin/sh -c apt update && apt install -y git && go get -f -u github.com/OWASP/Amass/...
root       1990  0.0  0.0      0     0 ?        I    15:34   0:00 [kworker/1:0-mm_percpu_wq]
root       1995  0.0  0.0      0     0 ?        I    15:36   0:00 [kworker/0:2-ata_sff]
root       2005  0.2  0.6 250964 20552 ?        Sl   15:38   0:00 go get -f -u github.com/OWASP/Amass/...
root       2627  0.0  0.0      0     0 ?        I    15:41   0:00 [kworker/0:0-mm_percpu_wq]
root       2701  0.0  0.1  15380  3460 ?        S    15:43   0:00 git clone https://github.com/gogo/protobuf /go/src/github.com/gogo/protobuf
root       2702  0.3  0.8 181264 27204 ?        S    15:43   0:00 git-remote-https origin https://github.com/gogo/protobuf
root       2704  0.0  0.0  23680  2912 ?        Sl   15:43   0:00 git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning
root       2706  0.0  0.1  18176  3652 ?        S    15:43   0:00 git index-pack --stdin --fix-thin --keep=fetch-pack 897 on c3f07cd12742 --check-self-contained-and-conne
root       2709  0.4  0.1   7852  4704 pts/1    Ss   15:44   0:00 bash
root       2715  0.0  0.0      0     0 ?        I    15:44   0:00 [kworker/1:1-events]
root       2717  0.0  0.1  10568  3144 pts/1    R+   15:44   0:00 ps aux

**Comment by c0rvax** [comment]
Thanks for checking. I will spin up an AWS Kali and see how it goes.

**Comment by c0rvax** [comment]
Right now, looking at your ps aux the notable part for me is 

```
root 2005 0.2 0.6 250964 20552 ? Sl 15:38 0:00 go get -f -u github.com/OWASP/Amass/...
root 2701 0.0 0.1 15380 3460 ? S 15:43 0:00 git clone https://github.com/gogo/protobuf /go/src/github.com/gogo/protobuf
root 2702 0.3 0.8 181264 27204 ? S 15:43 0:00 git-remote-https origin https://github.com/gogo/protobuf
root 2704 0.0 0.0 23680 2912 ? Sl 15:43 0:00 git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning
root 2706 0.0 0.1 18176 3652 ? S 15:43 0:00 git index-pack --stdin --fix-thin --keep=fetch-pack 897 on c3f07cd12742 --check-self-contained-and-conne
```

This looks like you are getting a hang while `go` is installing `Amass`, specifically when fetching dependencies.


I have checked on AWS kali and it works fine. Could you trying doing simply this on the same machine? ` go get -f -u github.com/OWASP/Amass/...`

**Comment by lovelyjuice** [comment]
You are right. The problem is that `go get` will pull at least 160MB data from github but the speed from china to AWS (where github repository data actually in) is very slow. And `go get` do not print any prompt, so it seems to processes hang on.

After I connected to vpn, the installer continued, and I can see the size of files that have been download increasing quickly.

Thanks to help me locate the problem!

**Comment by c0rvax** [comment]
Thanks for the verbose follow-up! Good we have resolved the issue. 

Please create a new issue if something else won't work for you. Would be happy to help
